### Signup
POST http://127.0.0.1:6000/api/auth/signup
Content-Type: application/json

{
  "name": "Test User",
  "email": "testuser@example.com",
  "password": "TestPassword123"
}

### Login
POST http://127.0.0.1:6000/api/auth/login
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "TestPassword123"
}

### Get All Products
GET http://localhost:6000/api/products
### Add Product (Admin only)
POST http://localhost:6000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGE0Mjk2ZDU5OTRiYzNiMWViMjYzNjEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc1NTU4OTAxOSwiZXhwIjoxNzU1NzYxODE5fQ.Pjt--PWXumOLi65nyJ5-ok9iv_fdOWOLSeYIGpyXBpU

{
  "name": "Product 1",
  "description": "Description for product 1",
  "price": 199.99,
  "stockQuantity": 100
}
